"""
Fibaro HC3 API Pydantic Models.

!!! GENERATED FILE — DO NOT EDIT BY HAND !!!

Regenerated by `src/plua/generate_typed_fibaro_api.py` from the vendored
Fibaro Swagger/OpenAPI specifications. Manual edits will be lost on the
next regeneration.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

# Generated Pydantic Models


class CreateSceneRequest(BaseModel):
    name: str | None = None
    description: str | None = None
    type_: str | None = Field(None, alias="type")
    mode: str | None = None
    icon: str | None = None
    content: str | None = None
    maxRunningInstances: int | None = None
    hidden: bool | None = None
    protectedByPin: bool | None = None
    stopOnAlarm: bool | None = None
    enabled: bool | None = None
    restart: bool | None = Field(
        ..., description="Allow to restart a running scene."
    )
    categories: list[int] | None = None
    scenarioData: ScenarioContent | None = None
    roomId: int | None = None


class ExecuteSceneRequest(BaseModel):
    alexaProhibited: bool | None = Field(
        ..., description="Execute scene by alexaProhibited"
    )
    args: dict[str, Any] | None = None


class FilterSceneRequest(BaseModel):
    pass


class CreateSceneResponse(BaseModel):
    id: int | None = None


class SceneDto(BaseModel):
    id: int | None = None
    name: str | None = None
    description: str | None = None
    type_: str | None = Field(None, alias="type")
    mode: str | None = None
    icon: str | None = None
    iconExtension: str | None = None
    content: str | None = None
    maxRunningInstances: int | None = None
    hidden: bool | None = None
    protectedByPin: bool | None = None
    scenarioData: ScenarioContent | None = None
    stopOnAlarm: bool | None = None
    enabled: bool | None = None
    restart: bool | None = Field(
        ..., description="Allow to restart a running scene."
    )
    categories: list[int] | None = None
    created: int | None = None
    updated: int | None = None
    isRunning: bool | None = Field(
        ..., description="If scene is running return true otherwise false."
    )
    isScenarioDataCorrect: bool | None = Field(
        ...,
        description="If scene is custom scenario and scenario data is incorrect, e.g. device was deleted",
    )
    started: int | None = Field(..., description="Timestamp of the scene start.")
    roomId: int | None = None
    sortOrder: int | None = None


class UpdateSceneRequest(BaseModel):
    name: str | None = None
    description: str | None = None
    mode: str | None = None
    maxRunningInstances: int | None = None
    icon: str | None = None
    content: str | None = None
    hidden: bool | None = None
    protectedByPin: bool | None = None
    stopOnAlarm: bool | None = None
    enabled: bool | None = None
    restart: bool | None = Field(
        ..., description="Allow to restart a running scene."
    )
    categories: list[int] | None = None
    scenarioData: ScenarioContent | None = None
    roomId: int | None = None


class ScenarioContent(BaseModel):
    type_: str | None = Field(None, alias="type")
    version: int | None = None
    when: ScenarioContentWhen | None = None
    where: ScenarioContentWhere | None = None
    what: ScenarioContentWhat | None = None
    trigger: ScenarioContentWhere | None = None
    turnOffDelay: int | None = None
    actions: list[dict[str, Any]] | None = None
    triggers: triggers | None = None
    conditions: conditions | None = None


class ScenarioContentWhen(BaseModel):
    daysOfWeek: list[str] | None = None
    exactTime: str | None = None
    afterTime: str | None = None
    timeOffset: int | None = None
    notEarlierThan: str | None = None
    notLaterThan: str | None = None


class ScenarioContentWhere(BaseModel):
    wholeHouse: bool | None = None
    sections: list[int] | None = None
    rooms: list[int] | None = None
    devices: list[int] | None = None


class ScenarioContentWhat(BaseModel):
    action: dict[str, Any] | None = None


class triggers(BaseModel):
    pass


class conditions(BaseModel):
    pass


class complexConditions(BaseModel):
    group: str | None = None
    type_: str | None = Field(None, alias="type")
    conditions: conditions
    operator: str


class deviceTriggerOrCondition(BaseModel):
    group: str
    type_: str = Field(..., alias="type")
    id: float
    property: str
    operator: str
    value: dict[str, Any]
    duration: float | None = None


class profileTriggerOrCondition(BaseModel):
    group: str
    type_: str = Field(..., alias="type")
    value: float
    property: str
    operator: str
    duration: float | None = None


class cronTriggerOrCondition(BaseModel):
    group: str
    type_: str = Field(..., alias="type")
    property: str
    operator: str
    value: dict[str, Any]


class cron(BaseModel):
    pass


class interval(BaseModel):
    date: cron
    interval: float


class weatherBasicCondition(BaseModel):
    group: str
    type_: str = Field(..., alias="type")
    value: float
    property: str
    operator: str
    duration: float | None = None


class weatherConditionsCondition(BaseModel):
    group: str
    type_: str = Field(..., alias="type")
    value: str
    property: str
    operator: str
    duration: float | None = None


class isDayOrNightCondition(BaseModel):
    group: str
    type_: str = Field(..., alias="type")
    operator: str
    value: bool
    property: str | None = None


class sunEventTrigger(BaseModel):
    group: str
    type_: str = Field(..., alias="type")
    property: str
    value: float
    operator: str


class deviceAction(BaseModel):
    group: str
    id: list[float]
    action: str
    args: list[dict[str, Any]]
    delay: float | None = None


class profileAction(BaseModel):
    group: str
    id: float
    action: str
    delay: float | None = None


class remoteControllerTrigger(BaseModel):
    group: str
    type_: str = Field(..., alias="type")
    id: float
    property: str
    value: dict[str, Any]
    operator: str


class DeviceIconDto(BaseModel):
    deviceType: str | None = None
    iconSetName: str | None = None
    id: int | None = None
    fileExtension: str | None = None


class RoomIconDto(BaseModel):
    iconName: str | None = None
    id: int | None = None
    fileExtension: str | None = None


class SceneIconDto(BaseModel):
    iconName: str | None = None
    id: int | None = None
    fileExtension: str | None = None


class CreatedIconDto(BaseModel):
    id: int | None = None
    iconSetName: str | None = None


class IconListDto(BaseModel):
    device: list[DeviceIconDto] | None = None
    room: list[RoomIconDto] | None = None
    scene: list[SceneIconDto] | None = None


class SortOrderRequest(BaseModel):
    from_: int | None = Field(None, alias="from")
    to_: int | None = Field(None, alias="to")
    fromSection: int | None = None
    toSection: int | None = None
    fromRoom: int | None = None
    toRoom: int | None = None
    fromType: str | None = None
    toType: str | None = None
    action: str | None = None


class FavoriteColor(BaseModel):
    id: int | None = None
    r: int | None = None
    g: int | None = None
    b: int | None = None
    w: int | None = None
    brightness: int | None = None
    created: int | None = None
    modified: int | None = None


class NewFavoriteColor(BaseModel):
    r: int | None = None
    g: int | None = None
    b: int | None = None
    w: int | None = None
    brightness: int | None = None


class RefreshStateDto(BaseModel):
    status: str | None = None
    last: int | None = None
    date: str | None = None
    timestamp: int | None = None
    logs: list[DebugMessageDto] | None = None
    events: list[dict[str, Any]] | None = None
    changes: list[dict[str, Any]] | None = None
    alarmChanges: list[dict[str, Any]] | None = None


class ProfileCreateDto(BaseModel):
    name: str | None = None
    iconId: int | None = None
    sourceId: int | None = None


class ProfileServiceDto(BaseModel):
    activeProfile: int | None = None
    profiles: list[ProfileDto] | None = None


class ProfileDto(BaseModel):
    id: int | None = None
    name: str | None = None
    iconId: int | None = None
    devices: list[DeviceActorDto] | None = None
    scenes: list[SceneActorDto] | None = None
    partitions: list[PartitionActionDto] | None = None
    climateZones: list[ClimateZonesActionDto] | None = None


class DeviceActorDto(BaseModel):
    id: int | None = None
    action: DeviceActionDto | None = None


class SceneActorDto(BaseModel):
    sceneId: int | None = None
    actions: list[action] | None = None


class PartitionActionDto(BaseModel):
    partitionId: int | None = None
    action: str | None = None


class ClimateZonesActionDto(BaseModel):
    id: int
    mode: ClimateZonesActionMode
    properties: ClimateZonesActionProperties | None = None


class ClimateZonesActionMode(BaseModel):
    pass


class ClimateZonesActionProperties(BaseModel):
    handSetPointHeating: float | None = Field(
        ..., description="Heating temperature for manual mode"
    )
    handSetPointCooling: float | None = Field(
        ..., description="Cooling temperature for manual mode"
    )
    handMode: ClimateZonesActionHandMode | None = None


class ClimateZonesActionHandMode(BaseModel):
    pass


class PartitionActionUpdateDto(BaseModel):
    action: str | None = None


class ClimateZoneActionUpdateDto(BaseModel):
    mode: ClimateZonesActionMode
    properties: ClimateZonesActionProperties | None = None


class SceneActorUpdateDto(BaseModel):
    actions: list[action] | None = None


class action(BaseModel):
    pass


class DeviceActionDto(BaseModel):
    name: str
    isUIAction: bool | None = None
    args: list[dict[str, Any]]


class CpuLoad(BaseModel):
    name: str | None = Field(..., description="CPU core name")
    idle: float | None = None
    nice: float | None = None
    system: float | None = None
    user: float | None = None


class Memory(BaseModel):
    buffers: int | None = None
    cache: int | None = None
    free: int | None = None
    used: int | None = None


class Storage(BaseModel):
    name: str | None = None
    used: int | None = None


class Diagnostic(BaseModel):
    cpuLoad: list[CpuLoad] | None = None
    memory: Memory | None = None
    storage: Diagnostic_storage | None = None


class Diagnostic_storage(BaseModel):
    internal: list[Storage] | None = None


class DiagnosticTransmissions(BaseModel):
    items: list[DiagnosticTransmissionsItem] | None = None
    since: float | None = None
    until: float | None = None


class DiagnosticTransmissionsItem(BaseModel):
    incomingFailedCrc: float | None = None
    incomingFailedDecryption: float | None = None
    incomingNonceGet: float | None = None
    incomingNonceReport: float | None = None
    incomingTimedOutNonce: float | None = None
    incomingTotal: float | None = None
    nodeId: float | None = None
    outgoingFailed: float | None = None
    outgoingNonceGet: float | None = None
    outgoingTotal: float | None = None


class UserCreateRequest(BaseModel):
    email: str | None = None
    name: str | None = None
    type_: str | None = Field(None, alias="type")


class UserDto(BaseModel):
    id: int | None = None
    name: str | None = None
    password: str | None = None
    pin: str | None = None
    passwordConfirm: str | None = None
    type_: str | None = Field(None, alias="type")
    email: str | None = None
    alarmRights: list[int] | None = None
    climateZoneRights: list[int] | None = None
    profileRights: list[int] | None = None
    raStatus: str | None = None
    isAdminTransferPossible: bool | None = None
    rights: UserDtoRights | None = None
    hotelRoom: int | None = None
    sendNotifications: bool | None = None
    tracking: int | None = None
    useOptionalArmPin: bool | None = None
    useIntegrationPin: bool | None = None
    integrationPin: str | None = None
    initialWizard: bool | None = None
    pendingAdminRoleTransfer: bool | None = None
    fidUuid: str | None = None
    fidLastSynchronizationTimestamp: int | None = None
    fidRole: str | None = None
    skin: str | None = None
    skinSetting: str | None = None
    isAddTileVisible: bool | None = None
    buiSettings: dict[str, Any] | None = None


class UserDtoRights(BaseModel):
    advanced: dict[str, Any] | None = None
    devices: dict[str, Any] | None = None
    scenes: dict[str, Any] | None = None
    alarmPartitions: dict[str, Any] | None = None
    profiles: dict[str, Any] | None = None
    climateZones: dict[str, Any] | None = None


class DebugMessagesDto(BaseModel):
    nextLast: float | None = None
    messages: list[DebugMessageDto] | None = None


class DebugMessageDto(BaseModel):
    id: int | None = None
    timestamp: int | None = None
    type_: str | None = Field(None, alias="type")
    tag: str | None = None
    message: str | None = None


class DefaultSensors(BaseModel):
    temperature: int | None = None
    humidity: int | None = None
    light: int | None = None


class IconColor(BaseModel):
    pass


class RoomCreateRequest(BaseModel):
    name: str
    sectionID: int
    category: str
    icon: str
    iconExtension: str | None = None
    iconColor: IconColor | None = None
    visible: bool | None = None


class RoomUpdateRequest(BaseModel):
    id: int | None = None
    name: str | None = None
    sectionID: int | None = None
    icon: str | None = None
    iconExtension: str | None = None
    iconColor: IconColor | None = None
    defaultSensors: DefaultSensors | None = None
    defaultThermostat: int | None = None
    sortOrder: int | None = None
    category: str | None = None
    visible: bool | None = None


class RoomDto(BaseModel):
    id: int | None = None
    name: str | None = None
    sectionID: int | None = None
    isDefault: bool | None = None
    visible: bool | None = None
    icon: str | None = None
    iconExtension: str | None = None
    iconColor: IconColor | None = None
    defaultSensors: DefaultSensors | None = None
    defaultThermostat: int | None = None
    sortOrder: int | None = None
    category: str | None = None


class RoomGroupAssignment(BaseModel):
    deviceIds: list[int] | None = None


class TimeIntervalEnum(BaseModel):
    pass


class ConsumptionMeasurementEnum(BaseModel):
    pass


class EnergyDeviceInfo(BaseModel):
    id: float | None = Field(..., description="Id of device")
    deleted: bool | None = Field(..., description="Is device deleted")
    roomId: float | None = Field(..., description="Id of room")
    mainEnergyMeter: bool | None = Field(..., description="Is main energy meter")


class EnergyValueDto(BaseModel):
    pass


class PowerValueDto(BaseModel):
    pass


class EnergyCostDto(BaseModel):
    pass


class DateTimeUnitDto(BaseModel):
    pass


class BillingDurationEnum(BaseModel):
    pass


class EnergyBillingPeriodDto(BaseModel):
    duration: BillingDurationEnum | None = Field(
        ...,
        description="How long the billing period lasts - curently only 1,2,3,6,12 months are supported",
    )
    startDate: str | None = Field(
        ..., description="Day at which billing period started: YYYY-MM-DD"
    )
    endDate: str | None = Field(
        ...,
        description="Day at which billing period ended: YYYY-MM-DD. This value is empty for current period.",
    )
    fixedCost: float | None = Field(..., description="Fixed cost per billing period")


class EnergyDeviceEntryDto(BaseModel):
    id: int | None = Field(..., description="id of device")
    name: str | None = Field(
        ...,
        description="name of device; this is important if record coresponds to device that is already deleted",
    )
    roomId: int | None = Field(
        ...,
        description="Id of room the device is in; this is important if record coresponds to device that is already deleted",
    )
    consumption: EnergyValueDto | None = None
    production: EnergyValueDto | None = None
    consumptionCost: EnergyCostDto | None = None
    productionCost: EnergyCostDto | None = None


class EnergyRoomEntryDto(BaseModel):
    id: int | None = Field(..., description="id of room")
    production: EnergyValueDto | None = None
    consumption: EnergyValueDto | None = None
    productionCost: EnergyCostDto | None = None
    consumptionCost: EnergyCostDto | None = None


class EnergyCategoryEntryDto(BaseModel):
    category: str | None = Field(..., description="name of category")
    production: EnergyValueDto | None = None
    consumption: EnergyValueDto | None = None
    productionCost: EnergyCostDto | None = None
    consumptionCost: EnergyCostDto | None = None


class EnergySummaryDto(BaseModel):
    production: EnergyValueDto | None = None
    consumption: EnergyValueDto | None = None
    productionCost: EnergyCostDto | None = None
    consumptionCost: EnergyCostDto | None = None
    topConsumingDevices: list[EnergyDeviceEntryDto] | None = None


class EnergyMetricsDto(BaseModel):
    productionPower: PowerValueDto | None = None
    consumptionPower: PowerValueDto | None = None


class EnergyDetailDto(BaseModel):
    energy: list[dict[str, Any]] | None = None


class EnergyRoomDetailDto(BaseModel):
    energy: list[dict[str, Any]] | None = None


class EnergyDeviceDetailDto(BaseModel):
    energy: list[dict[str, Any]] | None = None


class EnergyBillingSummaryTypesDto(BaseModel):
    currentBillingPeriod: EnergyBillingSummaryDto | None = None
    previousBillingPeriod: EnergyBillingSummaryDto | None = None


class EnergyBillingSummaryDto(BaseModel):
    startDate: DateTimeUnitDto | None = None
    endDate: DateTimeUnitDto | None = None
    productionCost: float | None = Field(
        ..., description="Cost of energy produced during billig period"
    )
    consumptionCost: float | None = Field(
        ..., description="Cost of energy consumed during billig period"
    )
    production: EnergyValueDto | None = None
    consumption: EnergyValueDto | None = None


class InstallationCostDto(BaseModel):
    id: int | None = Field(..., description="Id of installation cost")
    date: str | None = Field(..., description="YYYY-MM-DD")
    cost: float | None = Field(..., description="cost of installation >= 0")
    name: str | None = Field(..., description="installation cost name")


class DayEnum(BaseModel):
    pass


class EnergyAdditionalTariffDto(BaseModel):
    """represents kWh cost for specified period of time during week (from startTime to endTime in specified days)"""

    rate: float | None = Field(..., description="how much 1kWh costs")
    name: str | None = Field(..., description="name of tariff")
    startTime: str | None = Field(..., description="HH:mm")
    endTime: str | None = Field(
        ...,
        description="HH:mm if endTime<startTime it means next day (e.g.: from 23:00 till 03:00 next day)",
    )
    days: list[DayEnum] | None = None


class EnergyTariffDto(BaseModel):
    rate: float | None = Field(..., description="how much 1kWh costs")
    name: str | None = Field(..., description="name of main tariff")
    returnRate: float | None = Field(..., description="rate of return ")
    additionalTariffs: list[EnergyAdditionalTariffDto] | None = Field(
        ...,
        description="additionl tariffs for some time periods during week. The higher the tariff in the list, the more priority it has",
    )


class SavingsDetailsDto(BaseModel):
    periodStart: DateTimeUnitDto | None = None
    periodEnd: DateTimeUnitDto | None = None
    production: EnergyValueDto | None = None
    consumption: EnergyValueDto | None = None
    productionCost: EnergyCostDto | None = None
    consumptionCost: EnergyCostDto | None = None
    devices: list[EnergyDeviceEntryDto] | None = None


class SavingsSummaryDto(BaseModel):
    hasProduction: bool | None = Field(
        ..., description="Determines whether user has producing device"
    )
    installationCost: float | None = Field(
        ..., description="Installation cost (producing device only)"
    )
    averageReturn: float | None = Field(
        ..., description="Average return per billing period (producing device only)"
    )
    averageReturnPeriod: BillingDurationEnum | None = Field(
        ..., description="Billing period for average return (producing device only)"
    )
    alreadyReturned: float | None = Field(
        ..., description="An amount of produced energy in money (producing device only)"
    )
    currentPeriodCost: float | None = Field(
        ...,
        description="Cost of enrgy in current billing period (without producing device only)",
    )
    averageCost: float | None = Field(
        ...,
        description="Average cost of energy per billing period (without producing device only)",
    )
    averageCostPeriod: BillingDurationEnum | None = Field(
        ...,
        description="Billing period for average cost (without producing device only)",
    )
    currentYearCost: float | None = Field(
        ...,
        description="Cost of energy in current year (without producing device only)",
    )


class SavingsInstallationDto(BaseModel):
    period: DateTimeUnitDto | None = None
    production: EnergyValueDto | None = None
    productionCost: EnergyCostDto | None = None


class EcologySummaryDto(BaseModel):
    productionStart: str | None = Field(
        ..., description="Date when energy production has started"
    )
    selfSufficiency: float | None = Field(
        ...,
        description="Percentage value describing how many of produced energy is directly used by the household",
    )
    treesPlanted: float | None = Field(
        ..., description="Equivalent of produced energy in trees planted"
    )
    reductionCO2: float | None = Field(
        ..., description="Tons of CO2 reduced thanks to produced energy"
    )


class EcologyDetailsDto(BaseModel):
    periodStart: DateTimeUnitDto | None = None
    periodEnd: DateTimeUnitDto | None = None
    treesPlanted: float | None = Field(
        ..., description="Cumulative equivalent of produced energy in trees planted"
    )
    reductionCO2: float | None = Field(
        ..., description="Cumulative tons of CO2 reduced thanks to produced energy"
    )


class EnergySettingsDto(BaseModel):
    consumptionMeasurement: ConsumptionMeasurementEnum | None = None
    energyConsumptionMeters: list[float] | None = Field(
        ..., description="List of device ids set as energy consumption meters."
    )
    energyProductionMeters: list[float] | None = Field(
        ..., description="List of device ids set as energy production meters."
    )
    powerConsumptionMeters: list[float] | None = Field(
        ..., description="List of device ids set as power consumption meters."
    )
    powerProductionMeters: list[float] | None = Field(
        ..., description="List of device ids set as power production meters."
    )
    gridConsumptionMeters: list[float] | None = Field(
        ..., description="List of device ids set as grid energy consumption meters."
    )
    gridProductionMeters: list[float] | None = Field(
        ..., description="List of device ids set as grid energy production meters."
    )
    gridPowerConsumptionMeters: list[float] | None = Field(
        ..., description="List of device ids set as grid power consumption meters."
    )
    gridPowerProductionMeters: list[float] | None = Field(
        ..., description="List of device ids set as grid power production meters."
    )


class ResetRequestDto(BaseModel):
    recovery: bool | None = None


class Energy(BaseModel):
    id: int | None = None
    totalEnergy: float | None = None
    current: EnergyData | None = None
    total: EnergyData | None = None


class EnergyData(BaseModel):
    H: float | None = None
    D: float | None = None
    W: float | None = None
    M: float | None = None
    Y: float | None = None
    costH: float | None = None
    costD: float | None = None
    costW: float | None = None
    costM: float | None = None
    costY: float | None = None


class Temperature(BaseModel):
    id: int | None = None
    temperatureD: float | None = None
    temperatureH: float | None = None
    temperatureM: float | None = None
    temperatureW: float | None = None


class EnergyFromTo(BaseModel):
    pass


class DataTypeRoomsOrDevices(BaseModel):
    pass


class DataTypeSummaryOrCompare(BaseModel):
    pass


class TemperatureFromTo(BaseModel):
    pass


class CoFromToArray(BaseModel):
    pass


class CoFromTo(BaseModel):
    timestamp: float
    value: dict[str, Any]
    id: float


class SmokeFromTo(BaseModel):
    smoke: list[list[float]]
    temperature: list[list[float]]
    max: float


class ThermostatMode(BaseModel):
    pass


class ThermostatFromTo(BaseModel):
    targetLevel: list[list[float]]
    temperature: list[list[float]]
    thermostatMode: list[list[dict[str, Any]]]
    min: float
    max: float


class iOSDev(BaseModel):
    id: int | None = None
    name: str | None = None
    push: bool | None = None
    udid: str | None = None


class Weather(BaseModel):
    ConditionCode: int | None = None
    Humidity: float | None = None
    Temperature: float | None = None
    TemperatureUnit: str | None = None
    WeatherCondition: str | None = None
    WeatherConditionConverted: str | None = None
    Wind: float | None = None
    WindUnit: str | None = None


class NotificationType(BaseModel):
    pass


class ChannelType(BaseModel):
    pass


class IntervalType(BaseModel):
    pass


class NotificationsSettings(BaseModel):
    type_: NotificationType = Field(..., alias="type")
    active: bool
    label: str
    interval: dict[str, Any]
    channels: list[ChannelType]
    supportedChannels: list[ChannelType] | None = None
    users: list[int]
    supportedInterval: list[IntervalType] | None = None
    category: str | None = None


class DeviceNotificationsSettings(BaseModel):
    deviceId: int
    notifications: list[NotificationsSettings]


class SectionCreateRequest(BaseModel):
    id: int | None = None
    name: str | None = None


class SectionUpdateRequest(BaseModel):
    id: int | None = None
    name: str | None = None
    created: int | None = None
    modified: int | None = None
    sortOrder: int | None = None


class SectionDto(BaseModel):
    id: int | None = None
    name: str | None = None
    created: int | None = None
    modified: int | None = None
    sortOrder: int | None = None


class FavoriteColorV2(BaseModel):
    id: int
    colorComponents: dict[str, Any]
    brightness: int
    created: int | None = None
    modified: int | None = None


class NewFavoriteColorV2(BaseModel):
    colorComponents: dict[str, Any]
    brightness: int


class DeviceNetworkDataDto(BaseModel):
    ip: str | None = None
    mac: str | None = None
    vendor: str | None = None


class NetworkDiscoveryDto(BaseModel):
    mac: list[str] | None = None


class priorityEnum(BaseModel):
    pass


class NotificationCenterDto(BaseModel):
    id: int | None = Field(..., description="Notification unique id")
    priority: str | None = Field(
        ..., description="Notification priority: 'info', 'warning' or 'alert'"
    )
    wasRead: bool | None = Field(
        ...,
        description="Flag: if true: notification marked as read, if false: notification marked as unread",
    )
    canBeDeleted: bool | None = Field(
        ...,
        description="Flag:if true: notification can be deleted, if false: notification can't be deleted",
    )
    type_: str | None = Field(
        ...,
        alias="type",
        description="Notification type, each type of notification has its own data structure",
    )
    created: int | None = Field(
        ..., description="Timestamp: Date and time of creation"
    )
    data: NotificationCenterDataDto | None = None


class NotificationCenterRequestDto(BaseModel):
    priority: str | None = Field(
        ..., description="Notification priority: 'info', 'warning' or 'alert'"
    )
    wasRead: bool | None = Field(
        ...,
        description="Flag: if true: notification marked as read, if false: notification marked as unread",
    )
    canBeDeleted: bool | None = Field(
        ...,
        description="Flag:if true: notification can be deleted, if false: notification can't be deleted",
    )
    type_: str | None = Field(
        ...,
        alias="type",
        description="Notification type, each type of notification has its own data structure",
    )
    data: NotificationCenterDataDto | None = None


class NotificationCenterDataDto(BaseModel):
    """Data describing the characteristics of individual notifications. Data specific to particular types of notifications."""

    deviceId: int | None = Field(
        ...,
        description="Scene id associated with notification. Return SatelConfigurationRequest, FirmwareUpdateRequest and GenericDeviceRequest",
    )
    sceneId: int | None = Field(
        ...,
        description="Scene id associated with notification. Return for GenericSceneRequest",
    )
    taskId: int | None = Field(
        ...,
        description="Task id associated with notification. Return for ZwaveReconfigurationNotificationRequest",
    )
    title: str | None = Field(
        ...,
        description="Notification title. Return for GenericDeviceRequest and GenericSceneRequest",
    )
    text: str | None = Field(
        ...,
        description="Text describing the notification, visible in the notification center.Return for GenericDeviceRequest, \
            GenericSceneRequest and GenericSystemNotificationRequest",
    )
    name: str | None = Field(
        ...,
        description="Notification name. Return for GenericSystemNotificationRequest",
    )
    subType: str | None = Field(
        ...,
        description="Additional type for GenericSystemNotification. Possible options: 'Generic', 'EmailInvalid', 'DeviceNotConfigured', 'DeviceNoTemplate', \
            'NoFibaroPartitionInAlarm', 'ZwavePollingTime', 'UserNameDuplicated'. Return for GenericSystemNotificationRequest",
    )
    status: str | None = Field(
        ...,
        description="Notification status for FirmwareUpdateNotification. Possible options: 'Available', 'QueuedForUpdate', 'Downloading', 'WaitingForCommunication', \
        'Updating', 'UpdateOk', 'UpdateFail', 'UpToDate', 'QueuedForCheck'. Return for GenericSystemNotificationRequest",
    )
    url: str | None = Field(
        ...,
        description="Notification button url. Return for GenericSystemNotificationRequest",
    )
    urlText: str | None = Field(
        ...,
        description="Notification button text. Return for GenericSystemNotificationRequest",
    )
    info: str | None = Field(
        ...,
        description="Additional info about firmware update. Return for FirmwareUpdateRequest",
    )
    progress: int | None = Field(
        ...,
        description="Progress of the operation related to notification (in percent: 0-100). Return for SatelConfigurationRequest and FirmwareUpdateRequest",
    )
    icon: NotificationCenterDataIconDto | None = None


class NotificationCenterDataIconDto(BaseModel):
    """Notification icon. Return for GenericDeviceRequest"""

    path: str | None = Field(..., description="Path to icon file")
    source: str | None = Field(..., description="Icon source")


class ColorDto(BaseModel):
    b: int | None = None
    g: int | None = None
    r: int | None = None
    w: int | None = None


class StepDto(BaseModel):
    color: ColorDto | None = None
    duration: int | None = None
    transitionTime: int | None = None


class ProgramDto(BaseModel):
    id: int | None = None
    name: str | None = None
    totalDurationTime: float | None = None
    steps: list[StepDto] | None = None


class CreateProgramRequest(BaseModel):
    created: int | None = None
    id: int | None = None
    modified: int | None = None
    name: str | None = None
    steps: list[StepDto] | None = None
    totalDurationTime: int | None = None


class CreateQuickAppRequest(BaseModel):
    name: str | None = None
    type_: str | None = Field(None, alias="type")
    roomId: float | None = None
    initialProperties: dict[str, Any] | None = None
    initialInterfaces: list[str] | None = None
    initialView: dict[str, Any] | None = None


class QuickAvailableTypeDto(BaseModel):
    type_: str | None = Field(None, alias="type")
    label: str | None = None


class QuickAppFile(BaseModel):
    name: str | None = None
    type_: str | None = Field(None, alias="type")
    isOpen: bool | None = None
    isMain: bool | None = None


class QuickAppFileDetails(BaseModel):
    name: str | None = None
    type_: str | None = Field(None, alias="type")
    isOpen: bool | None = None
    isMain: bool | None = None
    content: str | None = None


class QuickAppExportRequest(BaseModel):
    encrypted: bool | None = Field(
        ..., description="If true encrypted file will be exported."
    )
    serialNumbers: list[str] | None = Field(
        ...,
        description="List of serial numbers with the possibility to import the quick app. Requires encrypted field to be true.",
    )


class HCErrorDto(BaseModel):
    type_: str | None = Field(None, alias="type")
    reason: str | None = None
    message: str | None = Field(
        ..., description="Datild infomations about an error."
    )


class Icon(BaseModel):
    path: str | None = None
    source: str | None = None
    overlay: str | None = None


class BlackBoxDto(BaseModel):
    fileName: str | None = None
    state: str | None = None
    timestamp: float | None = None


class DeviceListFiltersDto(BaseModel):
    filters: list[DeviceListFilterDto] = Field(
        ..., description="Set of device filters that all should be fulfilled"
    )
    attributes: dict[str, Any] = Field(
        ..., description="Defines which device attributes will be returned"
    )


class DeviceListFilterDto(BaseModel):
    filter_: str | None = Field(None, alias="filter")
    value: list[dict[str, Any]] | None = None


class DevicesInterfacesDto(BaseModel):
    devicesId: list[int] = Field(
        ...,
        description="List of device ids for which we want to add/delete interfaces.",
    )
    interfaces: list[str] = Field(
        ...,
        description="List of interfaces which we want to add/delete to/from devices.",
    )


class RateType(BaseModel):
    pass


class ButtonType(BaseModel):
    pass


class DoorLockMode(BaseModel):
    pass


class DeviceAvailableSceneDto(BaseModel):
    name: str | None = None
    sceneId: float | None = None


class DevicePropertiesDto(BaseModel):
    alarmLevel: int | None = None
    alarmType: int | None = None
    armed: bool | None = None
    autoOffChannel1: float | None = None
    autoOffChannel2: float | None = None
    zwaveResources: list[ResourceTypeDto] | None = None
    associationMode: int | None = None
    availableDoorLockModes: list[DoorLockMode] | None = None
    availablePositions: list[AvailablePosition] | None = None
    availableScenes: list[DeviceAvailableSceneDto] | None = None
    batteryLevel: int | None = None
    batteryLowNotification: bool | None = None
    blackBox: BlackBoxDto | None = None
    buttonHold: int | None = None
    buttonsType: ButtonType | None = None
    currentHumidity: int | None = None
    showFreezeAlarm: bool | None = None
    showFireAlarm: bool | None = None
    buttonType: dict[str, Any] | None = None
    configurationSourceDeviceId: float | None = None
    motorInversion: bool | None = None
    restoreStateAfterPowerShortage: bool | None = None
    voltageMeasurementReport: int | None = None
    steeringInversion: bool | None = None
    movingUpTime: int | None = None
    movingDownTime: int | None = None
    slatsRotationTime: int | None = None
    virtualBottomLimit: int | None = None
    cameraType: int | None = None
    categories: list[str] | None = None
    calibrationVariants: list[str] | None = None
    calibrated: bool | None = None
    centralSceneSupport: list[CentralScene] | None = None
    channel1: str | None = None
    channel2: str | None = None
    channel3: str | None = None
    channel4: str | None = None
    climateZoneHash: str | None = None
    climateZoneId: int | None = None
    configured: bool | None = None
    dead: bool | None = None
    position: str | None = None
    port: float | None = None
    strategy: str | None = None
    deadReason: str | None = None
    defInterval: int | None = None
    defaultPartyTime: int | None = None
    defaultTone: int | None = None
    defaultWateringTime: int | None = None
    deviceControlType: int | None = None
    deviceRole: DeviceRole | None = None
    deviceState: str | None = None
    supportedDeviceRoles: list[DeviceRole] | None = None
    deviceGroup: list[int] | None = None
    raStatus: str | None = None
    deviceGroupMaster: int | None = None
    deviceIcon: int | None = None
    devices: list[int] | None = None
    devicesInitializationProcess: str | None = None
    DeviceUID: str | None = None
    displayOnMainPage: int | None = None
    doorLockMode: DoorLockMode | None = None
    emailNotificationID: int | None = None
    emailNotificationType: int | None = None
    endPointId: int | None = None
    externalSensorConnected: bool | None = None
    favoritePositionsNativeSupport: bool | None = None
    favoritePositions: list[FavoritePositions] | None = None
    fgrgbwMode: str | None = None
    fidUuid: str | None = None
    fidLastSynchronizationTimestamp: int | None = None
    fidRole: str | None = None
    firmwareUpdate: DeviceFirmwareUpdateDto | None = None
    gatewayId: str | None = None
    humidityThreshold: int | None = None
    httpsEnabled: bool | None = None
    icon: Icon | None = None
    includeInEnergyPanel: bool | None = None
    inputToChannelMap: DeviceInputToChannelMapDto | None = None
    ip: str | None = None
    isLight: bool | None = None
    jpgPath: str | None = None
    lastBreached: float | None = None
    lastHealthy: float | None = None
    lastLoggedUser: float | None = None
    lastModerate: float | None = None
    liliOffCommand: str | None = None
    liliOnCommand: str | None = None
    linkedDeviceType: str | None = None
    localProtectionEnabledChannel1: bool | None = None
    localProtectionEnabledChannel2: bool | None = None
    localProtectionState: int | None = None
    localProtectionSupport: int | None = None
    log: str | None = None
    logTemp: str | None = None
    manufacturer: str | None = None
    markAsDead: bool | None = None
    maxInterval: int | None = None
    maxUsers: int | None = None
    maxValue: int | None = None
    maxVoltage: int | None = None
    minInterval: int | None = None
    minValue: int | None = None
    minVoltage: int | None = None
    mjpgPath: str | None = None
    mode: float | None = None
    model: str | None = None
    moveDownPath: str | None = None
    moveLeftPath: str | None = None
    moveRightPath: str | None = None
    moveStopPath: str | None = None
    moveUpPath: str | None = None
    networkStatus: str | None = None
    niceId: int | None = None
    niceProtocol: str | None = None
    nodeId: int | None = None
    numberOfSupportedButtons: int | None = None
    offset: str | None = None
    overridesSchedule: bool | None = None
    output1Id: float | None = None
    output2Id: float | None = None
    outputsChannelsConnected: bool | None = None
    panicMode: bool | None = None
    parameters: list[DevicePropertiesDto_parameters] | None = None
    parametersTemplate: float | None = None
    password: str | None = None
    pendingActions: bool | None = None
    pollingDeadDevice: bool | None = None
    pollingInterval: float | None = None
    pollingTimeSec: str | None = None
    power: float | None = None
    productInfo: str | None = None
    protectionExclusiveControl: float | None = None
    protectionExclusiveControlSupport: float | None = None
    protectionState: float | None = None
    protectionTimeout: float | None = None
    protectionTimeoutSupport: bool | None = None
    pushNotificationID: int | None = None
    pushNotificationType: float | None = None
    rateType: RateType | None = None
    refreshTime: int | None = None
    remoteId: int | None = None
    remoteGatewayId: int | None = None
    RFProtectionEnabledChannel1: bool | None = None
    RFProtectionEnabledChannel2: bool | None = None
    RFProtectionState: int | None = None
    RFProtectionSupport: int | None = None
    rtspPath: str | None = None
    rtspPort: int | None = None
    saveLogs: bool | None = None
    slatsRange: int | None = None
    slatsRangeMin: int | None = None
    slatsRangeMax: int | None = None
    storeEnergyData: bool | None = None
    saveToEnergyPanel: bool | None = None
    schedules: list[dict[str, Any]] | None = None
    securityLevel: str | None = None
    securitySchemes: list[str] | None = None
    sendStopAfterMove: bool | None = None
    serialNumber: str | None = None
    showEnergy: bool | None = None
    state: dict[str, Any] | None = None
    energy: float | None = None
    sipUserPassword: str | None = None
    sipDisplayName: str | None = None
    sipUserID: str | None = None
    sipUserEnabled: bool | None = None
    smsNotificationID: int | None = None
    smsNotificationType: float | None = None
    softwareVersion: str | None = None
    stepInterval: float | None = None
    supportedThermostatFanModes: list[str] | None = None
    supportedThermostatModes: list[str] | None = None
    supportedTones: list[dict[str, Any]] | None = None
    tamperMode: str | None = None
    targetLevel: float | None = None
    targetLevelDry: float | None = None
    targetLevelHumidify: float | None = None
    targetLevelMax: float | None = None
    targetLevelMin: float | None = None
    targetLevelStep: float | None = None
    targetLevelTimestamp: float | None = None
    thermostatFanMode: str | None = None
    thermostatFanOff: bool | None = None
    thermostatFanState: str | None = None
    thermostatMode: str | None = None
    thermostatModeFuture: str | None = None
    thermostatOperatingState: str | None = None
    thermostatModeManufacturerData: list[int] | None = None
    thermostatState: str | None = None
    powerConsumption: float | None = None
    timestamp: int | None = None
    tone: int | None = None
    unit: str | None = None
    updateVersion: str | None = None
    useTemplate: bool | None = None
    userCodes: list[UserCodeDto] | None = None
    userDescription: str | None = None
    username: str | None = None
    wakeUpTime: float | None = None
    zwaveCompany: str | None = None
    zwaveInfo: str | None = None
    zwaveScheduleClimatePanelCompatibileBlocks: list[dict[str, Any]] | None = None
    zwaveVersion: str | None = None
    value: dict[str, Any] | None = None
    viewLayout: dict[str, Any] | None = None
    volume: int | None = None
    mainFunction: str | None = None
    uiCallbacks: list[dict[str, Any]] | None = None
    quickAppVariables: list[dict[str, Any]] | None = None
    colorComponents: dict[str, Any] | None = None
    walliOperatingMode: str | None = None
    ringUpperColor: str | None = None
    ringBottomColor: str | None = None
    ringBrightness: float | None = None
    ringLightMode: str | None = None
    ringConfirmingTime: float | None = None
    encrypted: bool | None = None
    useUiView: bool | None = None
    uiView: dict[str, Any] | None = None
    Humidity: float | None = None
    Pressure: float | None = None
    Temperature: float | None = None
    Wind: float | None = None
    ConditionCode: float | None = None
    WeatherCondition: str | None = None


class DeviceActionArgumentsDto(BaseModel):
    args: list[Any] | None = None
    delay: float | None = None  # Now truly optional
    integrationPin: str | None = None  # Now truly optional


class ResourceTypeDto(BaseModel):
    name: str
    type_: float = Field(..., alias="type")
    scales: list[float]
    rateType: float | None = None


class DeviceInputToChannelMapDto(BaseModel):
    close: list[float] | None = None
    open: list[float] | None = None
    partialOpen1: list[float] | None = None
    step: list[float] | None = None
    stop: list[float] | None = None
    toggleCh1: list[float] | None = None
    toggleCh2: list[float] | None = None
    turnOffCh1: list[float] | None = None
    turnOffCh2: list[float] | None = None
    turnOnCh1: list[float] | None = None
    turnOnCh2: list[float] | None = None
    unsupported: list[float] | None = None


class PluginCreateDto(BaseModel):
    name: str = Field(..., description="Name of device to be created")
    type_: str = Field(
        ..., alias="type", description="Plugin device type to be created"
    )
    roomID: int | None = Field(
        ...,
        description="Room ID to which device will be added; default room when not given",
    )
    properties: DevicePropertiesDto | None = None


class DeviceDto(BaseModel):
    actions: dict[str, Any] | None = None
    baseType: str | None = None
    configXml: bool | None = None
    created: int | None = None
    enabled: bool | None = None
    hasUIView: bool | None = None
    id: int | None = None
    interfaces: list[str] | None = None
    isPlugin: bool | None = None
    modified: int | None = None
    name: str | None = None
    parentId: float | None = None
    properties: DevicePropertiesDto | None = None
    roomID: int | None = None
    sortOrder: int | None = None
    type_: str | None = Field(None, alias="type")
    viewXml: bool | None = None
    view: list[ViewConfig] | None = None
    visible: bool | None = None


class DeviceInfoDto(BaseModel):
    id: int | None = None
    name: str | None = None
    classification: DeviceClassificationDto | None = None
    roomId: int | None = None
    type_: str | None = Field(None, alias="type")
    properties: list[DeviceInfoPropertyDto] | None = None
    role: str | None = None
    actions: list[DeviceInfoPropertyDto] | None = None
    events: list[dict[str, Any]] | None = None


class DeviceClassificationDto(BaseModel):
    pass


class DeviceInfoPropertyDto(BaseModel):
    name: dict[str, Any] | None = None
    type_: str | None = Field(None, alias="type")
    conditionType: list[dict[str, Any]] | None = None
    operator: str | None = None
    picker: str | None = None
    label: str | None = None
    unitPath: str | None = None
    unit: str | None = None
    min: float | None = None
    max: float | None = None
    step: float | None = None
    args: list[DeviceInfoPropertyDto] | None = None
    enumValues: DeviceInfoPropertyEnumValuesDto | None = None
    valueMapping: list[ValueMappingDto] | None = None
    isUIAction: bool | None = None
    definedValues: list[DeviceInfoPropertyDefinedValue] | None = None
    description: str | None = None
    colorComponents: DeviceInfoPropertyColorComponents | None = None


class DeviceInfoPropertyEnumValuesDto(BaseModel):
    items: list[dict[str, Any]] | None = None
    type_: str | None = Field(None, alias="type")
    key: str | None = None


class ValueMappingDto(BaseModel):
    value: bool
    label: str


class DeviceFirmwareUpdateDto(BaseModel):
    info: str | None = None
    progress: int | None = None
    status: str | None = None
    updateVersion: str | None = None


class GroupActionArguments(BaseModel):
    args: list[dict[str, Any]] | None = Field(
        ..., description="Action arguments if needed"
    )
    filters: list[dict[str, Any]] | None = Field(
        ..., description="Filters definitions for devices"
    )
    integrationPin: str | None = Field(..., description="Cloud integration pin")


class CentralScene(BaseModel):
    keyAttributes: list[KeyAttribute] | None = None
    keyId: float | None = None


class KeyAttribute(BaseModel):
    pass


class NewDevice(BaseModel):
    name: str | None = None
    properties: DevicePropertiesDto | None = None
    type_: str | None = Field(None, alias="type")


class DevicePropertiesDto_parameters(BaseModel):
    lastReportedValue: float | None = None
    size: float | None = None
    lastSetValue: float | None = None
    id: float | None = None
    value: float | None = None
    readyOnly: bool | None = None
    setDefault: bool | None = None


class UserCodeDto(BaseModel):
    id: float | None = None
    name: str | None = None
    status: str | None = None
    update: str | None = None


class ViewConfig(BaseModel):
    type_: str = Field(..., alias="type")
    assetsPath: str | None = None
    translatesPath: str | None = None
    name: str | None = None


class FavoritePositions(BaseModel):
    name: str | None = None
    label: str | None = None
    value: float | None = None
    slatsAngle: float | None = None


class AvailablePosition(BaseModel):
    name: str | None = None
    label: str | None = None


class DeviceRole(BaseModel):
    pass


class DeviceTypeHierarchy(BaseModel):
    type_: str | None = Field(None, alias="type")
    children: list[dict[str, Any]] | None = Field(
        ..., description="Items are of type DeviceTypeHierarchy"
    )


class DeviceInfoPropertyDefinedValue(BaseModel):
    unit: str | None = None
    values: list[dict[str, Any]] | None = None


class DeviceInfoPropertyDefinedColorComponent(BaseModel):
    brightness: float | None = None
    color: str | None = None
    colorComponents: dict[str, Any] | None = None
    label: str | None = None


class DeviceInfoPropertyColorComponents(BaseModel):
    blue: DeviceInfoPropertyColorComponentsComponent | None = None
    green: DeviceInfoPropertyColorComponentsComponent | None = None
    red: DeviceInfoPropertyColorComponentsComponent | None = None
    warmWhite: DeviceInfoPropertyColorComponentsComponent | None = None
    coldWhite: DeviceInfoPropertyColorComponentsComponent | None = None
    amber: DeviceInfoPropertyColorComponentsComponent | None = None
    cyan: DeviceInfoPropertyColorComponentsComponent | None = None
    purple: DeviceInfoPropertyColorComponentsComponent | None = None


class DeviceInfoPropertyColorComponentsComponent(BaseModel):
    label: str | None = None
    min: float | None = None
    max: float | None = None


class ViewVersionEnum(BaseModel):
    pass


class DevicesDto(BaseModel):
    pass


class SystemStatusDto(BaseModel):
    description: str | None = None
    os: str | None = None
    stage: SystemStatusStageDto | None = None
    current: int | None = None
    done: bool | None = None
    max: int | None = None
    status: str | None = None
    title: str | None = None
    update: SystemStatusUpdateDto | None = None
    platform: str | None = None
    oemId: str | None = None


class SystemStatusStageDto(BaseModel):
    description: str | None = None
    current: int | None = None
    done: bool | None = None
    max: int | None = None


class SystemStatusUpdateDto(BaseModel):
    type_: str | None = Field(None, alias="type")
    version: str | None = None


class SystemStatusAction(BaseModel):
    pass


class HomeDto(BaseModel):
    timestamp: float | None = None
    defaultSensors: HomeDto_defaultSensors | None = None
    meters: HomeDto_meters | None = None
    notificationClient: HomeDto_notificationClient | None = None
    hcName: str | None = None
    weatherProvider: float | None = None
    currency: str | None = None
    fireAlarmTemperature: float | None = None
    freezeAlarmTemperature: float | None = None
    timeFormat: float | None = None
    dateFormat: str | None = None
    firstRunAfterUpdate: bool | None = None


class HomeDto_defaultSensors(BaseModel):
    light: float | None = None
    temperature: float | None = None
    humidity: float | None = None


class HomeDto_meters(BaseModel):
    energy: list[float] | None = None


class HomeDto_notificationClient(BaseModel):
    marketingNotificationAllowed: bool | None = None


class UserActivityDto(BaseModel):
    email: str | None = None
    lastActivity: int | None = None
    type_: str | None = Field(None, alias="type")
    user: str | None = None
    userId: int | None = None


class LoginStatus(BaseModel):
    status: bool | None = None
    type_: str | None = Field(None, alias="type")
    userID: int | None = None
    username: str | None = None
    role: str | None = None
    analyticsUserIdHash: str | None = None
    skin: str | None = None
    skinSetting: str | None = None
    isAddTileVisible: bool | None = None
    buiSettings: dict[str, Any] | None = None
    rights: UserDtoRights | None = None


class LogoutStatus(BaseModel):
    status: bool | None = None
    retryNumber: int | None = None
    limit: int | None = None
    timeLeft: int | None = None


class PluginViewDto(BaseModel):
    field__jason: dict[str, Any] | None = Field(None, alias="$jason")


class PluginBodyDto(BaseModel):
    sections: PluginSectionsDto | None = None
    header: PluginHeaderDto | None = None


class PluginHeaderDto(BaseModel):
    title: str | None = Field(..., description="Page title")
    style: dict[str, Any] | None = None


class PluginSectionsDto(BaseModel):
    items: list[dict[str, Any]] | None = None


class PluginButtonDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    text: str | None = Field(
        ..., description="The Text displayed as the content of the button"
    )
    visible: bool | None = None
    type_: str | None = Field(None, alias="type")
    style: dict[str, Any] | None = None
    image: str | None = Field(..., description="Button image")
    classes: list[str] | None = None
    eventBinding: dict[str, Any] | None = None


class PluginHorizontalLayoutDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    type_: str | None = Field(None, alias="type")
    components: list[dict[str, Any]] | None = None
    style: dict[str, Any] | None = None


class PluginImageDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    type_: str | None = Field(None, alias="type")
    url: str | None = Field(..., description="Path to image")
    style: dict[str, Any] | None = None


class PluginLabelDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    type_: str | None = Field(None, alias="type")
    text: str | None = Field(
        ..., description="The text to be displayed inside of the label."
    )
    style: dict[str, Any] | None = None


class PluginMultiSelectDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    type_: str | None = Field(None, alias="type")
    text: str | None = Field(
        ..., description="The text to be displayed next to component."
    )
    selectionType: str | None = None
    style: dict[str, Any] | None = None
    options: list[PluginOptionDto] | None = None
    values: list[str] | None = None


class PluginOptionDto(BaseModel):
    value: str | None = Field(..., description="Option value.")
    type_: str | None = Field(None, alias="type")
    text: str | None = Field(..., description="The text to be displayed.")


class PluginSingleSelectDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    type_: str | None = Field(None, alias="type")
    text: str | None = Field(
        ..., description="The text to be displayed next to component."
    )
    selectionType: str | None = None
    style: dict[str, Any] | None = None
    options: list[PluginOptionDto] | None = None
    values: list[str] | None = None


class PluginSliderDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    type_: str | None = Field(None, alias="type")
    max: str | None = Field(..., description="The maximum selectable value.")
    min: str | None = Field(..., description="The minimum selectable value.")
    step: str | None = Field(..., description="The step between values.")
    value: str | None = Field(..., description="The chosen value.")
    style: dict[str, Any] | None = None


class PluginSpaceDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    type_: str | None = Field(None, alias="type")
    style: dict[str, Any] | None = None


class PluginSwitchDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    type_: str | None = Field(None, alias="type")
    value: str | None = None
    style: dict[str, Any] | None = None


class PluginVerticalLayoutDto(BaseModel):
    name: str | None = Field(..., description="Component name")
    type_: str | None = Field(None, alias="type")
    components: list[dict[str, Any]] | None = None
    style: dict[str, Any] | None = None


class PluginsTypesDto(BaseModel):
    installed: InstalledPluginsDto | None = None
    all: dict[str, Any] | None = None
    promo: list[dict[str, Any]] | None = None


class PluginUpdateDto(BaseModel):
    deviceId: int
    componentName: str
    propertyName: str
    newValue: str | int | float | bool | dict[str, Any] | list[Any]


class PluginsV2Dto(BaseModel):
    pass


class PluginV2ElementDto(BaseModel):
    compatibility: list[str] | None = None
    defaultMainDeviceName: str | None = None
    description: str | None = None
    type_: str | None = Field(None, alias="type")
    url: str | None = None
    author: str | None = None
    version: str | None = None
    name: str | None = None
    manufacturer: str | None = None
    model: str | None = None
    category: str | None = None
    icon: IconDto | None = None


class IconDto(BaseModel):
    path: str | None = None


class PluginsDto(BaseModel):
    installed: list[InstalledPluginElementDto] | None = None
    all: AllPluginsDto | None = None
    promo: list[PluginsPromoElementDto] | None = None


class IPCameraDto(BaseModel):
    id: str | None = None
    manufacturer: str | None = None
    model: str | None = None


class InstalledPluginsDto(BaseModel):
    pass


class InstalledPluginElementDto(BaseModel):
    name: str | None = Field(..., description="Installed plugin name")
    predefined: bool | None = Field(
        ..., description="Describes whether the plugin is predefined in the system."
    )


class AllPluginsDto(BaseModel):
    types: list[PluginByCategoryDto] | None = None


class PluginByCategoryDto(BaseModel):
    category: float | None = None
    plugins: list[PluginDto] | None = None
    installed: float | None = None


class PluginDto(BaseModel):
    type_: str | None = Field(None, alias="type")
    name: str | None = None
    defaultMainDeviceName: str | None = None
    description: str | None = None
    user: str | None = None
    compatibility: list[str] | None = None
    predefined: bool | None = None
    version: str | None = None
    url: str | None = None
    installed: bool | None = None


class PluginsPromoDto(BaseModel):
    pass


class PluginsPromoElementDto(BaseModel):
    image: PluginsPromoElementImageDto | None = None
    predefined: str | None = None


class PluginsPromoElementImageDto(BaseModel):
    big: str | None = None
    small: str | None = None


class UiEventType(BaseModel):
    pass


class CreateChildDeviceDto(BaseModel):
    parentId: int = Field(..., description="Parent id")
    type_: str = Field(..., alias="type", description="Type")
    name: str = Field(..., description="Name")
    initialProperties: dict[str, Any] | None = Field(
        ..., description="Initial properties"
    )
    initialInterfaces: list[str] | None = None


class UpdatePropertyDto(BaseModel):
    deviceId: int
    propertyName: str
    value: dict[str, Any] | None = None


class ZwaveNodeRemovedEventDto(BaseModel):
    type_: str = Field(..., alias="type", description="Type")
    data: dict[str, Any]


class CentralSceneEventDto(BaseModel):
    type_: str = Field(..., alias="type", description="Type")
    source: int = Field(..., description="Device id")
    data: dict[str, Any]


class DeviceFirmwareUpdateEventDto(BaseModel):
    type_: str = Field(..., alias="type", description="Type")
    source: int = Field(..., description="Device id")
    data: dict[str, Any]


class SceneActivationEventDto(BaseModel):
    type_: str = Field(..., alias="type", description="Type")
    source: int = Field(..., description="Device id")
    data: dict[str, Any]


class ZwaveNetworkResetEventDto(BaseModel):
    type_: str = Field(..., alias="type", description="Type")


class AccessControlEventDto(BaseModel):
    type_: str = Field(..., alias="type", description="Type")
    source: int = Field(..., description="Device id")
    data: dict[str, Any]


class VideoGateIncomingCallEventDto(BaseModel):
    type_: str = Field(..., alias="type", description="Type")
    data: dict[str, Any]


class ZwaveDeviceParametersChangedEventDto(BaseModel):
    type_: str = Field(..., alias="type", description="Type")
    source: int = Field(..., description="Device id")


class GeofenceEventDto(BaseModel):
    type_: str = Field(..., alias="type", description="Type")
    userId: int = Field(..., description="User id")
    deviceId: int = Field(..., description="Device id")
    locationId: int = Field(..., description="Location id")
    geofenceAction: str = Field(..., description="Geofence action")
    timestamp: int = Field(..., description="timestamp")


class PluginsInterfaceParamDto(BaseModel):
    action: str = Field(..., description="Action")
    deviceId: int = Field(..., description="Device id")
    interfaces: list[str] = Field(..., description="Interfaces to add or remove")


class RestartPluginRequestDto(BaseModel):
    deviceId: int = Field(..., description="Device id")


class RestartPluginResponseDto(BaseModel):
    status: bool = Field(..., description="Request status")


class LocationSettingsDate(BaseModel):
    """Current date on your device"""

    day: int | None = Field(..., description="Day")
    month: int | None = Field(..., description="Month")
    year: int | None = Field(..., description="Year")


class LocationSettingsTime(BaseModel):
    """Current time on your device"""

    hour: int | None = Field(..., description="Hour, format depends on timeFormat")
    minute: int | None = Field(..., description="Minute, format mm")


class LocationSettings(BaseModel):
    houseNumber: int | None = Field(..., description="Your location house number")
    timezone: str | None = Field(..., description="Your location time zone")
    timezoneOffset: int | None = Field(
        ...,
        description="Time zone difference, in minutes, from current locale (host system settings) to UTC",
    )
    ntp: bool | None = Field(..., description="Is NTP enabled")
    ntpServer: str | None = Field(
        ..., description="Network Time Protocol Server address"
    )
    date: LocationSettingsDate | None = None
    time: LocationSettingsTime | None = None
    longitude: float | None = Field(
        ..., description="The longitude of the location in EPSG:4326 coordinate system"
    )
    latitude: float | None = Field(
        ..., description="The latitude of the location in EPSG:4326 coordinate system"
    )
    city: str | None = Field(..., description="City")
    temperatureUnit: str | None = Field(
        ..., description="Temperature Unit: Celsius (C) or Fahrenheit(F)"
    )
    windUnit: str | None = Field(..., description="Wind unit")
    timeFormat: int | None = Field(..., description="Time format: 12 or 24")
    dateFormat: str | None = Field(..., description="Date format")
    decimalMark: str | None = Field(..., description="Decimal mark")


class LedDto(BaseModel):
    brightness: int | None = None


class interfaces(BaseModel):
    interfaces: list[str] | None = None


class ipConfig(BaseModel):
    ipMode: str
    ip: str | None = None
    mask: str | None = None
    gateway: str | None = None
    dns1: str | None = None
    dns2: str | None = None
    macAddress: str | None = None


class apConfig(BaseModel):
    ssid: str
    security: str
    password: str | None = None
    fallback: bool | None = None
    hidden: bool | None = None
    signal: int | None = None
    bssid: str | None = None
    frequency: int | None = None


class interfaceConfiguration(BaseModel):
    enabled: bool
    ipConfig: ipConfig | None = None
    apConfig: apConfig | None = None


class configN(BaseModel):
    pass


class networkConfiguration(BaseModel):
    networkConfig: configN | None = None


class ap(BaseModel):
    ssid: str
    signal: int | None = None
    security: list[str]


class apInfo(BaseModel):
    ssid: str
    bssid: str | None = None
    frequency: int | None = None
    signal: int | None = None
    apMode: str | None = None
    security: list[str]


class apList(BaseModel):
    apList: list[ap] | None = None


class apListInfo(BaseModel):
    apListInfo: list[apInfo] | None = None


class accessPointMode(BaseModel):
    accessPointEnabled: bool | None = None


class protocols(BaseModel):
    http: bool
    https: bool


class internetConnectivity(BaseModel):
    internetConnectivity: bool


class connections(BaseModel):
    pass


class connection(BaseModel):
    uuid: str | None = None
    name: str
    enabled: bool
    status: str | None = None
    apConfig: apConfig | None = None
    ipConfig: ipConfig | None = None


class statusResponse(BaseModel):
    code: int
    message: str


class radioConfiguration(BaseModel):
    enabled: bool


class radioListConfiguration(BaseModel):
    pass


class remoteAccessState(BaseModel):
    active: bool
    deadline: int | None = None
    supportUser: bool | None = None


class remoteAccessStatus(BaseModel):
    user: remoteAccessState | None = None
    support: remoteAccessState | None = None


class Settings(BaseModel):
    pass


class CurrentVersion(BaseModel):
    version: str | None = None
    type_: str | None = Field(None, alias="type")


class InstallVersion(BaseModel):
    version: str | None = None
    type_: str | None = Field(None, alias="type")
    status: str | None = None
    progress: int | None = None


class Info(BaseModel):
    serialNumber: str | None = None
    platform: str | None = None
    zwaveEngineVersion: ZwaveEngineVersion | None = None
    zigbeeStatus: bool | None = None
    hcName: str | None = None
    mac: str | None = None
    zwaveVersion: str | None = None
    timeFormat: int | None = None
    dateFormat: str | None = None
    timezoneOffset: int | None = None
    decimalMark: str | None = None
    zwaveRegion: ZwaveRegion | None = None
    serverStatus: int | None = None
    defaultLanguage: str | None = None
    defaultRoomId: int | None = None
    sunsetHour: str | None = None
    sunriseHour: str | None = None
    hotelMode: bool | None = None
    temperatureUnit: str | None = None
    batteryLowNotification: bool | None = None
    date: str | None = None
    currency: str | None = None
    softVersion: str | None = None
    beta: bool | None = None
    currentVersion: CurrentVersion | None = None
    installVersion: InstallVersion | None = None
    timestamp: int | None = None
    online: bool | None = None
    updateStableAvailable: bool | None = None
    updateBetaAvailable: bool | None = None
    newestStableVersion: str | None = None
    newestBetaVersion: str | None = None
    isFTIConfigured: bool | None = None
    skin: str | None = None
    skinSetting: str | None = None
    isSlave: bool | None = None
    oemId: OemId | None = None


class ZwaveEngineVersion(BaseModel):
    pass


class ZwaveRegion(BaseModel):
    pass


class OemId(BaseModel):
    pass


class AlarmHistoryEntryDto(BaseModel):
    type_: str | None = Field(..., alias="type", description="Event type.")
    partitionId: float | None = Field(
        ..., description="Partition id which generated the entry."
    )
    userId: float | None = Field(
        ...,
        description="Field required for PartitionArmed and PartitionDisarmed types. Does not occur in PartitionBreached.",
    )
    deviceId: float | None = Field(
        ...,
        description="Field required for PartitionBreached type. Does not occur in PartitionArmed and PartitionDisarmed.",
    )
    timestamp: float | None = Field(..., description="Creation time.")


class NewPartitionDto(BaseModel):
    name: str
    armDelay: int
    breachDelay: int
    devices: list[int]


class AlarmPartitionDto(BaseModel):
    id: int
    name: str
    armed: bool
    breached: bool
    armDelay: float
    breachDelay: float
    devices: list[int]
    secondsToArm: int | None = None
    lastActionAt: int | None = None


class PartitionArmTryResult(BaseModel):
    id: int
    result: PartitionArmState
    armTime: int | None = None
    breachedDevices: list[int] | None = None


class PartitionArmState(BaseModel):
    pass


class inline_response_201(BaseModel):
    id: int | None = None


class AlarmDeviceEntryDto(BaseModel):
    id: float | None = None
    name: str | None = None


class HumiditySetpoint(BaseModel):
    hour: int | None = None
    minute: int | None = None
    humidity: float | None = None


class HumidityScheduleDay(BaseModel):
    day: HumiditySetpoint | None = None
    evening: HumiditySetpoint | None = None
    morning: HumiditySetpoint | None = None
    night: HumiditySetpoint | None = None


class HumidityScheduleWeek(BaseModel):
    currentHumidity: float | None = None
    handHumidity: float | None = None
    handTimestamp: int | None = None
    vacationHumidity: float | None = None
    rooms: list[int] | None = None
    monday: HumidityScheduleDay | None = None
    tuesday: HumidityScheduleDay | None = None
    wednesday: HumidityScheduleDay | None = None
    thursday: HumidityScheduleDay | None = None
    friday: HumidityScheduleDay | None = None
    saturday: HumidityScheduleDay | None = None
    sunday: HumidityScheduleDay | None = None


class HumidityZone(BaseModel):
    id: int | None = None
    name: str | None = None
    created: int | None = None
    modified: int | None = None
    properties: HumidityScheduleWeek | None = None


class inline_object(BaseModel):
    name: str | None = None


class Location(BaseModel):
    id: int | None = Field(..., description="Location Id")
    name: str = Field(..., description="Location name")
    address: str | None = Field(..., description="Location addres")
    longitude: float | None = Field(
        ..., description="The longitude of the location in EPSG:4326 coordinate system"
    )
    latitude: float | None = Field(
        ..., description="The latitude of the location in EPSG:4326 coordinate system"
    )
    radius: int | None = Field(..., description="Map radius in meters")
    home: bool | None = Field(
        ...,
        description="Location type. If 'true': Home location, if 'false': Other location. There can be only one Home Location",
    )
    created: int | None = Field(
        ..., description="Timestamp: Date and time of creation"
    )
    modified: int | None = Field(
        ..., description="Timestamp: Date and time of last modification"
    )


class LocationRequest(BaseModel):
    name: str = Field(..., description="Location name")
    address: str | None = Field(..., description="Location addres")
    longitude: float | None = Field(
        ..., description="The longitude of the location in EPSG:4326 coordinate system"
    )
    latitude: float | None = Field(
        ..., description="The latitude of the location in EPSG:4326 coordinate system"
    )
    radius: int | None = Field(..., description="Map radius in meters")


class Day(BaseModel):
    pass


class sprinklers_DayEnum(BaseModel):
    pass


class SprinklerZone(BaseModel):
    deviceId: int | None = None
    duration: int | None = Field(..., description="seconds")


class SprinklerSequenceRequest(BaseModel):
    startTime: int | None = Field(..., description="seconds from midnight")
    sprinklers: list[SprinklerZone] | None = None


class SprinklerSequence(BaseModel):
    id: int | None = None
    isRunning: bool | None = None
    startTime: int | None = Field(..., description="seconds from midnight")
    sprinklers: list[SprinklerZone] | None = None


class SprinklerSequenceStartWateringRequest(BaseModel):
    wateringTime: int | None = None


class SprinklerSchedule(BaseModel):
    id: int | None = None
    name: str | None = None
    isActive: bool | None = None
    days: Day | None = None
    sequences: list[SprinklerSequence] | None = None


class SprinklerScheduleCreateRequest(BaseModel):
    name: str | None = None


class SprinklerScheduleRequest(BaseModel):
    name: str | None = None
    days: Day | None = None
    sequences: list[SprinklerSequenceRequest] | None = None
    isActive: bool | None = None


class FamilyLocation(BaseModel):
    timestamp: int | None = None
    latitude: float | None = None
    longitude: float | None = None


class Notifications(BaseModel):
    pass


class Notification(BaseModel):
    id: int | None = None
    name: str | None = None
    sms: str | None = None
    email: str | None = None
    push: str | None = None
    created: int | None = None
    modified: int | None = None


class notifications_inline_object(BaseModel):
    name: str | None = None


class CustomEventDto(BaseModel):
    name: str | None = None
    userDescription: str | None = None


class GlobalVariableDto(BaseModel):
    enumValues: list[str] | None = None
    isEnum: bool | None = None
    name: str | None = None
    readOnly: bool | None = None
    value: str | None = None


class PanelMode(BaseModel):
    pass


class CalculationStrategy(BaseModel):
    pass


class Mode(BaseModel):
    pass


class ClimateSetpoint(BaseModel):
    """Temperature settings for period of time"""

    hour: int | None = None
    minute: int | None = None
    temperatureHeating: float | None = None
    temperatureCooling: float | None = None


class ClimateScheduleDay(BaseModel):
    """Periods of time during the day"""

    morning: ClimateSetpoint | None = None
    day: ClimateSetpoint | None = None
    evening: ClimateSetpoint | None = None
    night: ClimateSetpoint | None = None


class BasicProperties(BaseModel):
    mode: Mode | None = None
    handSetPointHeating: float | None = Field(
        ..., description="Heating temperature for manual mode"
    )
    handSetPointCooling: float | None = Field(
        ..., description="Cooling temperature for manual mode"
    )
    handTimestamp: int | None = Field(
        ..., description="End date and time for manual mode (timestamp)"
    )
    handMode: Mode | None = None
    vacationSetPointHeating: float | None = Field(
        ..., description="Heating temperature for vacation mode"
    )
    vacationSetPointCooling: float | None = Field(
        ..., description="Cooling temperature for vacation mode"
    )
    vacationMode: Mode | None = None
    vacationStartTime: float | None = Field(
        ..., description="Start date and time for vacation mode (timestamp)"
    )
    vacationEndTime: float | None = Field(
        ..., description="End date and time for vacation mode (timestamp)"
    )
    currentTemperature: float | None = Field(
        ..., description="Current temperature settings"
    )
    currentTemperatureHeating: float | None = Field(
        ..., description="Current temperature settings for heating"
    )
    currentTemperatureCooling: float | None = Field(
        ..., description="Current temperature settings for cooling"
    )
    currentSetpointTimeStartHour: float | None = Field(
        ..., description="Current hour of range start"
    )
    currentSetpointTimeStartMinute: float | None = Field(
        ..., description="Current minute of range start"
    )
    currentSetpointTimeEndHour: float | None = Field(
        ..., description="Current hour of range end"
    )
    currentSetpointTimeEndMinute: float | None = Field(
        ..., description="Current minute of range end"
    )


class AdvancedProperties(BaseModel):
    mode: Mode | None = None
    monday: ClimateScheduleDay | None = None
    tuesday: ClimateScheduleDay | None = None
    wednesday: ClimateScheduleDay | None = None
    thursday: ClimateScheduleDay | None = None
    friday: ClimateScheduleDay | None = None
    saturday: ClimateScheduleDay | None = None
    sunday: ClimateScheduleDay | None = None
    handSetPointHeating: float | None = Field(
        ..., description="Heating temperature for manual mode"
    )
    handSetPointCooling: float | None = Field(
        ..., description="Cooling temperature for manual mode"
    )
    handTimestamp: int | None = Field(
        ..., description="End date and time for manual mode (timestamp)"
    )
    handMode: Mode | None = None
    vacationSetPointHeating: float | None = Field(
        ..., description="Heating temperature for vacation mode"
    )
    vacationSetPointCooling: float | None = Field(
        ..., description="Cooling temperature for vacation mode"
    )
    vacationMode: Mode | None = None
    vacationStartTime: float | None = Field(
        ..., description="Start date and time for vacation mode (timestamp)"
    )
    vacationEndTime: float | None = Field(
        ..., description="End date and time for vacation mode (timestamp)"
    )
    currentTemperatureHeating: float | None = Field(
        ..., description="Current temperature settings for heating"
    )
    currentTemperatureCooling: float | None = Field(
        ..., description="Current temperature settings for cooling"
    )
    currentSetpointTimeStartHour: float | None = Field(
        ..., description="Current hour of range start"
    )
    currentSetpointTimeStartMinute: float | None = Field(
        ..., description="Current minute of range start"
    )
    currentSetpointTimeEndHour: float | None = Field(
        ..., description="Current hour of range end"
    )
    currentSetpointTimeEndMinute: float | None = Field(
        ..., description="Current minute of range end"
    )
    devices: list[int] | None = None
    incompatibleDevices: list[int] | None = None
    temperatureSensors: list[int] | None = Field(
        ...,
        description="List of temperature sensors that will be used in calculatig currentTemperature",
    )
    calculationStrategy: CalculationStrategy | None = None
    currentTemperature: float | None = Field(
        ..., description="Current calculated temperature in climate zone"
    )


class BasicClimateZone(BaseModel):
    id: int | None = Field(..., description="Climate zone id")
    name: str | None = Field(..., description="Climate zone name")
    active: bool | None = Field(..., description="Is climate zone active")
    mode: PanelMode | None = None
    properties: BasicProperties | None = None


class AdvancedClimateZone(BaseModel):
    id: int | None = Field(..., description="Climate zone id")
    name: str | None = Field(..., description="Climate zone name")
    active: bool | None = Field(..., description="Is climate zone active")
    mode: PanelMode | None = None
    created: int | None = Field(
        ..., description="Timestamp: Date and time of creation"
    )
    modified: int | None = Field(
        ..., description="Timestamp: Date and time of modification"
    )
    properties: AdvancedProperties | None = None


class CreatePushRequest(BaseModel):
    mobileDevices: list[int] = Field(..., description="List of push receivers.")
    title: str = Field(..., description="Push title.")
    message: str = Field(..., description="Push message")
    category: str = Field(..., description="Push category")
    service: str | None = Field(..., description="Service where action will be run.")
    action: str | None = Field(
        ...,
        description="Action which will be run on the service. Value depends on service value.",
    )
    data: dict[str, Any] = Field(..., description="Push data.")


class FactoryResetRequestBody(BaseModel):
    ticket: str | None = Field(..., description="RA ticket")
    deleteBackups: bool | None = Field(
        ..., description="Flag indicating whether stored backups should be removed"
    )
    detachFibaroId: bool | None = Field(
        ...,
        description="Flag indicating whether HC should be detached from cloud account",
    )


class SourceType(BaseModel):
    pass


class EventDto(BaseModel):
    id: int | None = None
    sourceType: SourceType | None = None
    sourceId: int | None = None
    timestamp: int | None = None
    type_: str | None = Field(None, alias="type")
    data: dict[str, Any] | None = None
    objects: list[dict[str, Any]] | None = None


# Note: The add_extra_blank_lines_between_classes function was moved to the generator script
# to avoid self-modification at import time which breaks installed packages.
