-- Demo script showing the new REPL options
print("🚀 PLua REPL Options Demo")
print("")
print("PLua now supports two REPL modes:")
print("")
print("1. Interactive REPL (recommended): -i or --interactive")
print("   • Uses stdin/stdout with prompt_toolkit")
print("   • Works well in terminals and VS Code")
print("   • Enhanced editing with history and syntax highlighting")
print("")
print("2. Telnet Server: --telnet")
print("   • Starts a telnet server on port 8023")
print("   • Allows remote connections")
print("   • Multiple clients can connect simultaneously")
print("")
print("Usage examples:")
print("  ./run.sh -i                    # Start interactive REPL")
print("  ./run.sh --interactive         # Same as above")
print("  ./run.sh --telnet              # Start telnet server")
print("  ./run.sh script.lua --telnet   # Run script with telnet server")
print("")
print("This demo will exit in 3 seconds...")

_PY.setTimeout(function()
    print("Demo finished!")
end, 3000)
