name: Build Executables

# DISABLED - Executable building temporarily disabled
# on:
#   release:
#     types: [published]
#   workflow_dispatch:  # Allow manual trigger

on:
  workflow_dispatch:  # Only allow manual trigger
    inputs:
      force_build:
        description: 'Force build executables (set to "yes" to enable)'
        required: true
        default: 'no'

jobs:
  build-executables:
    if: github.event.inputs.force_build == 'yes'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
          - os: windows-latest
            platform: windows
            arch: x86_64
          - os: macos-latest
            platform: macos
            arch: x86_64
          - os: macos-14  # Apple Silicon
            platform: macos
            arch: arm64

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install nuitka
    
    - name: Build with Nuitka
      run: |
        cd scripts
        python build_nuitka.py
    
    - name: Prepare artifacts
      shell: bash
      run: |
        mkdir -p artifacts
        
        # Find built executables
        if [ "${{ matrix.platform }}" = "windows" ]; then
          EXT=".exe"
        else
          EXT=""
        fi
        
        # Nuitka output  
        if [ -f "scripts/plua.dist/plua${EXT}" ]; then
          cp "scripts/plua.dist/plua${EXT}" "artifacts/plua-${{ matrix.platform }}-${{ matrix.arch }}${EXT}"
        elif [ -f "scripts/plua${EXT}" ]; then
          cp "scripts/plua${EXT}" "artifacts/plua-${{ matrix.platform }}-${{ matrix.arch }}${EXT}"
        fi
        
        # List what we built
        ls -la artifacts/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plua-${{ matrix.platform }}-${{ matrix.arch }}
        path: artifacts/
        retention-days: 90
    
    - name: Upload to release (if release)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
