name: Build Executables

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-executables:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
          - os: windows-latest
            platform: windows
            arch: x86_64
          - os: macos-latest
            platform: macos
            arch: x86_64
          - os: macos-14  # Apple Silicon
            platform: macos
            arch: arm64

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[build]
        
    - name: Install platform-specific dependencies
      run: |
        # Install platform-specific requirements for Nuitka
        if [ "${{ matrix.platform }}" = "linux" ]; then
          sudo apt-get update
          sudo apt-get install -y gcc g++ ccache
        elif [ "${{ matrix.platform }}" = "macos" ]; then
          # macOS should have Xcode command line tools available
          echo "Using macOS system compiler"
        elif [ "${{ matrix.platform }}" = "windows" ]; then
          # Windows should use MSVC
          echo "Using Windows MSVC compiler"
        fi
      shell: bash
    
    - name: Build with Nuitka
      run: |
        cd scripts
        echo "Building for platform: ${{ matrix.platform }}-${{ matrix.arch }}"
        echo "Python version: $(python --version)"
        echo "Nuitka version: $(python -m nuitka --version)"
        echo "Current directory: $(pwd)"
        echo "Files in scripts directory:"
        ls -la
        echo "Checking if build_main_standalone.py exists:"
        ls -la build_main_standalone.py
        python build_nuitka.py
      shell: bash
    
    - name: Prepare artifacts
      shell: bash
      run: |
        mkdir -p artifacts
        
        # Find built executables from Nuitka
        if [ "${{ matrix.platform }}" = "windows" ]; then
          EXT=".exe"
        else
          EXT=""
        fi
        
        # Check for different possible Nuitka output locations
        if [ "${{ matrix.platform }}" = "macos" ]; then
          # macOS creates .app bundles
          if [ -d "scripts/dist/build_main_standalone.app" ]; then
            # Copy the entire app bundle for macOS
            cp -r "scripts/dist/build_main_standalone.app" "artifacts/plua-${{ matrix.platform }}-${{ matrix.arch }}.app"
            # Also extract just the executable for convenience
            if [ -f "scripts/dist/build_main_standalone.app/Contents/MacOS/plua" ]; then
              cp "scripts/dist/build_main_standalone.app/Contents/MacOS/plua" "artifacts/plua-${{ matrix.platform }}-${{ matrix.arch }}${EXT}"
            fi
          fi
        else
          # Linux/Windows create single files
          if [ -f "scripts/dist/plua${EXT}" ]; then
            cp "scripts/dist/plua${EXT}" "artifacts/plua-${{ matrix.platform }}-${{ matrix.arch }}${EXT}"
          fi
        fi
        
        # List what we built
        ls -la artifacts/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plua-${{ matrix.platform }}-${{ matrix.arch }}
        path: artifacts/
        retention-days: 90
    
    - name: Upload to release (if release)
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
