name: Build macOS Intel Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos-intel:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          echo "Installing requirements..."
          pip install -r requirements.txt
          echo "Installing PyInstaller..."
          pip install pyinstaller
          echo "Checking installed packages..."
          pip list

      - name: Test lupa import
        run: python -c "import lupa; print('Lupa import successful')"

      - name: Build executable with PyInstaller (Intel)
        run: |
          pyinstaller --onefile \
            --collect-submodules lupa \
            --collect-submodules toml \
            --collect-submodules plua \
            --collect-submodules extensions \
            src/plua/__main__.py \
            --name plua \
            --add-data "src/lua:lua" \
            --add-data "src/extensions:extensions" \
            --add-data "examples:examples" \
            --add-data "pyproject.toml:." \
            --target-arch=x86_64

      - name: Verify architecture
        run: |
          file dist/plua
          echo "Architecture verification:"
          file dist/plua | grep -q "x86_64" && echo "✓ Intel x86_64 confirmed" || echo "⚠ Architecture verification failed"

      - name: Test executable
        run: |
          chmod +x dist/plua
          ./dist/plua --version

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: plua-macos-intel-exe
          path: dist/plua 