name: Publish Python Package to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Extract version from tag
      id: get_version
      run: |
        # Remove 'v' prefix if present (e.g., v1.0.54 -> 1.0.54)
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version: $VERSION"
    
    - name: Update version in __init__.py
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        sed -i "s/__version__ = \".*\"/__version__ = \"$VERSION\"/" src/plua/__init__.py
        echo "Updated version to: $VERSION"
        grep "__version__" src/plua/__init__.py
    
    - name: Build package
      run: python -m build
    
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        verbose: true
