name: Release Pipeline

# DISABLED - Executable building temporarily disabled
# on:
#   release:
#     types: [published]

on:
  workflow_dispatch:  # Only allow manual trigger
    inputs:
      force_build:
        description: 'Force build executables (set to "yes" to enable)'
        required: true
        default: 'no'

jobs:
  # Job 1: Build executables
  build-executables:
    if: github.event.inputs.force_build == 'yes'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
          - os: windows-latest
            platform: windows
            arch: x86_64
          - os: macos-latest
            platform: macos
            arch: x86_64
          - os: macos-14
            platform: macos
            arch: arm64

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install nuitka
    
    - name: Build with Nuitka
      run: |
        cd scripts
        python build_nuitka.py
    
    - name: Prepare release artifacts
      shell: bash
      run: |
        mkdir -p release-artifacts
        
        if [ "${{ matrix.platform }}" = "windows" ]; then
          EXT=".exe"
        else
          EXT=""
        fi
        
        # Package Nuitka build
        if [ -f "scripts/plua.dist/plua${EXT}" ]; then
          cp "scripts/plua.dist/plua${EXT}" "release-artifacts/plua-${{ matrix.platform }}-${{ matrix.arch }}${EXT}"
        elif [ -f "scripts/plua${EXT}" ]; then
          cp "scripts/plua${EXT}" "release-artifacts/plua-${{ matrix.platform }}-${{ matrix.arch }}${EXT}"
        fi
        
        ls -la release-artifacts/
    
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: release-artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Job 2: Update release with summary (runs after build completes)
  update-release:
    needs: [build-executables]
    runs-on: ubuntu-latest
    steps:
    - name: Update release description
      uses: softprops/action-gh-release@v1
      with:
        append_body: true
        body: |
          
          ## 📦 Installation Options
          
          ### Python Package (Recommended)
          ```bash
          pip install plua==${{ github.ref_name }}
          ```
          
          > **Note**: PyPI package is published automatically by a separate workflow.
          
          ### Standalone Executables
          Download the appropriate executable for your platform:
          - **Linux**: `plua-linux-x86_64`
          - **Windows**: `plua-windows-x86_64.exe` 
          - **macOS Intel**: `plua-macos-x86_64`
          - **macOS Apple Silicon**: `plua-macos-arm64`
          
          All executables are optimized builds compiled with Nuitka.
          
          ### Usage
          ```bash
          # Python package
          plua script.lua
          
          # Standalone executable
          ./plua-linux-x86_64 script.lua
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
