name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Test lupa import
        run: python test_lupa_simple.py

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --collect-submodules lupa --collect-submodules toml plua.py --name plua --add-data "lua;lua" --add-data "extensions;extensions" --add-data "examples;examples" --add-data "demos;demos" --add-data "pyproject.toml;."

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: plua-windows-exe
          path: dist/plua.exe 