name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller lupa paho-mqtt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile plua.py --name plua \
            --add-data "lua;lua" \
            --add-data "extensions;extensions" \
            --add-data "examples;examples" \
            --add-data "demos;demos"
        # If your entry point is in plua/interpreter.py, change to: pyinstaller --onefile plua/interpreter.py --name plua ...

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: plua-windows-exe
          path: dist/plua.exe 