name: Build Windows Executable

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Generate PyInstaller spec file
        run: python build_windows_spec.py

      - name: Build executable with PyInstaller
        run: pyinstaller plua.spec

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: plua-windows-exe
          path: dist/plua.exe 